
const CURRENCY_SYMBOLS: Record<string, string> = {
    // Major currencies
    'USD': '$',
    'EUR': '€',
    'GBP': '£',
    'JPY': '¥',
    'CNY': '¥',
    'CHF': '₣',
    'CAD': 'C$',
    'AUD': 'A$',
    'NZD': 'NZ$',
    'SEK': 'kr',
    'NOK': 'kr',
    'DKK': 'kr',
    'PLN': 'zł',
    'CZK': 'Kč',
    'HUF': 'Ft',
    'RUB': '₽',
    'INR': '₹',
    'KRW': '₩',
    'SGD': 'S$',
    'HKD': 'HK$',
    'THB': '฿',
    'MYR': 'RM',
    'IDR': 'Rp',
    'PHP': '₱',
    'VND': '₫',
    'BRL': 'R$',
    'MXN': '$',
    'ARS': '$',
    'CLP': '$',
    'COP': '$',
    'PEN': 'S/',
    'ZAR': 'R',
    'EGP': 'E£',
    'TRY': '₺',
    'ILS': '₪',
    'SAR': '﷼',
    'AED': 'د.إ',
    'QAR': 'ر.ق',
    'KWD': 'د.ك',
    'BHD': '.د.ب',
    'OMR': 'ر.ع.',
    'JOD': 'د.ا',
    'LBP': 'ل.ل',
    'PKR': '₨',
    'BDT': '৳',
    'LKR': '₨',
    'NPR': '₨',
    'BTN': 'Nu.',
    'AFN': '؋',
    'IRR': '﷼',
    'IQD': 'ع.د',
    'SYP': 'ل.س',
    'YER': '﷼',
    'MAD': 'د.م.',
    'TND': 'د.ت',
    'DZD': 'د.ج',
    'LYD': 'ل.د',
    'SDG': 'ج.س.',
    'ETB': 'Br',
    'KES': 'KSh',
    'UGX': 'USh',
    'TZS': 'TSh',
    'RWF': 'RF',
    'BIF': 'FBu',
    'DJF': 'Fdj',
    'SOS': 'Sh.So.',
    'ERN': 'Nfk',
    'GHS': 'GH₵',
    'NGN': '₦',
    'XOF': 'CFA',
    'XAF': 'FCFA',
    'GMD': 'D',
    'SLE': 'Le',
    'LRD': 'L$',
    'CIV': 'CFA',
    'GNF': 'FG',
    'SLL': 'Le',
    'MRU': 'UM',
    'CVE': '$',
    'STN': 'Db',
    'AOA': 'Kz',
    'MZN': 'MT',
    'SZL': 'L',
    'LSL': 'L',
    'BWP': 'P',
    'NAD': 'N$',
    'ZMW': 'ZK',
    'ZWL': 'Z$',
    'MWK': 'MK',
    'MGA': 'Ar',
    'KMF': 'CF',
    'SCR': '₨',
    'MUR': '₨',
    'MVR': '.ރ'
};

export function getCurrencySymbol(currencyCode: string, fallback?: string): string {
    if (!currencyCode) {
        return fallback || '$';
    }

    const upperCode = currencyCode.toString().toUpperCase().trim();
    return CURRENCY_SYMBOLS[upperCode] || fallback || upperCode;
}

export const currencyData = [
    {
        "id": "cml53wbyg003nnz01whsx3khy",
        "currency": "INR",
        "last4": "6765",
        "accountNumber": "9273362376765",
        "userId": "cmicqu0lg001wqh01s0v3okvw",
        "createdAt": "2026-02-02T11:48:37.385Z",
        "updatedAt": "2026-03-02T09:32:29.353Z"
    },
    {
        "id": "cml53e79n003lnz01jgmbadb5",
        "currency": "GBP",
        "last4": "3623",
        "accountNumber": "672363623",
        "userId": "cmicqu0lg001wqh01s0v3okvw",
        "createdAt": "2026-02-02T11:34:31.499Z",
        "updatedAt": "2026-02-26T11:46:28.756Z"
    },
    {
        "id": "cmkw9nm4t001vpk01htaubv3j",
        "currency": "AUD",
        "last4": "4726",
        "accountNumber": "9827364726",
        "userId": "cmicqu0lg001wqh01s0v3okvw",
        "createdAt": "2026-01-27T07:19:52.782Z",
        "updatedAt": "2026-02-26T11:45:37.607Z"
    },
    {
        "id": "cmkw9n822001tpk01xrk0jh7z",
        "currency": "CAD",
        "last4": "3893",
        "accountNumber": "7632563893",
        "userId": "cmicqu0lg001wqh01s0v3okvw",
        "createdAt": "2026-01-27T07:19:34.539Z",
        "updatedAt": "2026-01-27T07:19:34.539Z"
    }
]

export const currencyList = [
    { code: 'EUR', label: `${getCurrencySymbol('EUR')} EUR (Euro)` },
    { code: 'USD', label: `${getCurrencySymbol('USD')} USD (US Dollar)` },
    { code: 'GBP', label: `${getCurrencySymbol('GBP')} GBP (British Pound)` },
    { code: 'CAD', label: `${getCurrencySymbol('CAD')} CAD (Canadian Dollar)` },
    { code: 'AUD', label: `${getCurrencySymbol('AUD')} AUD (Australian Dollar)` },
    { code: 'JPY', label: `${getCurrencySymbol('JPY')} JPY (Japanese Yen)` },
    { code: 'CHF', label: `${getCurrencySymbol('CHF')} CHF (Swiss Franc)` },
    { code: 'INR', label: `${getCurrencySymbol('INR')} INR (Indian Rupee)` },
]
